### ISSUE TITLE
Unable to see bumble servers on raspberry pi

### ISSUE THREAD

**Issue by michael-barrow** [google/bumble#106]
I want to connect the virtual heart rate server example to my raspberry pi running Raspberry Pi OS as a virtual device. My goal is to be able to see the the virtual device from the built-in bluetooth controller, so I can use bumble to emulate a bluetooth LE heart rate monitor.

I've tried to start with run_controller.py from the examples by following the [README.md](https://github.com/google/bumble/tree/main/examples) instructions. But I ran into some problems.

I do not have a USB dongle since I just want to use the built in bluetooth. This seems to mess everything up as I get the following error:

```
python run_controller.py F2:F3:F4:F5:F6:F7 device1.json usb:0`


DEBUG:asyncio:Using selector: EpollSelector
 connecting to HCI...
Traceback (most recent call last):
  File "/home/pi/Workspace/bumble/examples/run_controller.py", line 106, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/pi/Workspace/bumble/examples/run_controller.py", line 52, in main
    async with await open_transport_or_link(sys.argv[3]) as (hci_source, hci_sink):
  File "/home/pi/Workspace/bumble/bumble/transport/__init__.py", line 123, in open_transport_or_link
    return await open_transport(name)
  File "/home/pi/Workspace/bumble/bumble/transport/__init__.py", line 95, in open_transport
    return await open_usb_transport(spec[0] if spec else None)
  File "/home/pi/Workspace/bumble/bumble/transport/usb.py", line 429, in open_usb_transport
    raise ValueError('device not found')
ValueError: device not found
```

 That makes sense since hciconfig says

```
hci0:	Type: Primary  Bus: UART
	BD Address: B8:27:EB:7B:B5:EE  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:51481 acl:0 sco:0 events:2143 errors:0
	TX bytes:8873 acl:0 sco:0 commands:733 errors:0
```

But I can't do `python run_controller.py F2:F3:F4:F5:F6:F7 device1.json uart*` since it is not supported.

What is the best way to move forward?

**Comment by michael-barrow** [comment]
I have been digging into this more and if I use the same commands listed below, I can reproduce the unsupported command error on Ubuntu MATE 22.04. I have tried the pypi repository version of bumble as well as version 0.0.1.

### Operating system and software

OS: Ubuntu Mate 22.04
Bluez: 5.64 (also see issue with 5.50)
bumble: 0.0.1, 0.0.136, 0.0.137.dev3+g17db5dd

### Steps to reproduce

Download any of the aforementioned tags
Install bumble: `cd $BUMBLEROOT; python3 -m pip install -e . `
Attempt to create virtual bluetooth controller: `cd examples;  python3 run_controller.py F0:F1:F2:F3:F4:F5 device1.json pty:hci_pty`
Connect bluez to virtual bluetooth controller (in another terminal): `cd $BUMBLEROOT/examples; sudo btattach -P h4 -B hci_pty`
List hci controllers (in another terminal): `hciconfig`

### Expected output

something similar to

```
hci*:	Type: Primary  Bus: UART
	BD Address: F0:F1:F2:F3:F4:F5  ACL MTU: 1021:4  SCO MTU: 96:6
	UP RUNNING PSCAN 
	RX bytes:11 acl:40 sco:0 events:26 errors:0
	TX bytes:11 acl:67 sco:0 commands:25 errors:0
```

This controller should be visible to `bluetoothctl` for use with virtual devices

### Observed output

The virtual controller never comes up and therefore cannot be seen by `bluetoothctl`

```
hci1:	Type: Primary  Bus: UART
	BD Address: 00:00:00:00:00:00  ACL MTU: 27:64  SCO MTU: 0:0
	DOWN 
	RX bytes:190 acl:0 sco:0 events:12 errors:0
	TX bytes:64 acl:0 sco:0 commands:12 errors:0

```

**Comment by barbibulle** [comment]
Hi.
Attaching an HCI PTY to the BlueZ stack does work, but there's an even simpler way to attach a virtual controller to the BlueZ stack, using the `vhci` interface (see https://google.github.io/bumble/platforms/linux.html#using-vhci).
That being said, I'm not sure if attaching a virtual controller to the BlueZ stack is exactly what you're looking for. From your first post, you say that you want to "see the the virtual device from the built-in bluetooth controller". That's not really possible as described. You can't really mix physical and virtual controllers. Physical controllers can communicate with other physical controllers, and virtual controllers communicate with virtual controllers. The bumble stack can be used in either mode. If you want a virtual device using a virtual controller (in your example, a heart rate monitor) to be "seen" by the Linux BlueZ stack, you would attach both your virtual heart rate monitor and the BlueZ stack to the same virtual controller, so that they can see each other. Using the "link relay" (https://google.github.io/bumble/apps_and_tools/link_relay.html) is a way to have several virtual controllers communicate with each other (that part of the project may be a bit rusty, let us know if you use it and run into issues, we may need to fix a couple things). The other option is, of course, to have two physical controllers on your machine (the builtin one and an additional one, like a USB dongle), and have those two controllers communicate with each other.
I hope that clarifies things somewhat. We can continue the discussion on this thread once we clarify which of the two scenarios mentioned here best fits what you're trying to do.

**Comment by michael-barrow** [comment]
Thanks for the response, I'm a novice with bluetooth so I may have been unclear. 

My goal is to have an application which has access to the raspberry pi OS bluetooth stack (bluez?) see the virtual device so I can emulate various virtual capabilities in the virtual device for use in developing a bluetooth enabled application.

`vhci` sounds great for this. I had tried your suggesion (https://google.github.io/bumble/platforms/linux.html#using-vhci) but, it does not work on my pi.

I do see a virtual controller listed by `hciconfig`, but am unable to bring up that virtual controller. The steps to reproduce are the same as my second post except that I specify the `vhci` protocol rather than the `hci_pty` protocol.

Because I have seen the same problem on Ubuntu and Raspberry pi OS with different version of bumble and bluez, I think maybe I am experiencing operator error, but I can't determine what step(s) I am missing. Maybe you can verify these steps your side?

My exact steps are:


### Raspberry pi Terminal A 
```python3 examples/run_controller.py F6:F7:F8:F9:FA:FB examples/device1.json vhci
```

### Raspberry pi Terminal B
```
hciconfig
hci1:	Type: Primary  Bus: Virtual
	BD Address: 00:00:00:00:00:00  ACL MTU: 27:64  SCO MTU: 0:0
	DOWN 
	RX bytes:0 acl:0 sco:0 events:11 errors:0
	TX bytes:64 acl:0 sco:0 commands:11 errors:0

hci0:	Type: Primary  Bus: UART
	BD Address: B8:27:EB:7B:B5:EE  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING PSCAN 
	RX bytes:1568388 acl:0 sco:0 events:56495 errors:0
	TX bytes:98471 acl:0 sco:0 commands:11391 errors:0

```

This diverges from the example link in that the virtual controller is down. Unfortunately `hciconfig` cannot bring up the controller:

```
sudo hciconfig hci1 up
Can't init device hci1: Invalid request code (56)
```

This invalid request is (I think) the same issue I had seen with the uart interface.

Please let me know some things I could try to root cause this,

Cheers!

**Comment by barbibulle** [comment]
I think I found the issue. I don't have a raspberry pi to test on (they're hard to get these days, and mine broke), but I'll test the fix on some other linux host and post a PR shortly.

**Comment by barbibulle** [comment]
The fix has been merged now. If you can try again, let me know if it works for you.

**Comment by barbibulle** [comment]
Hi. The 00:00:00:00:00:00 BD address here isn't a concern, that only applies to Bluetooth Classic, but in your case you're working with Bluetooth Low Energy (BLE).
What you're trying to do should be entirely possible. Your app would use Linux's BlueZ stack (via whatever library you choose) and communicate with a virtual heart rate monitor written in Python with Bumble. For that to work, the virtual controller attached to the BlueZ stack and the virtual controller attached to the Bumble stack need to communicate with each other (in a non-virtual setting, "real" controllers would communicate via their radios). In the VHCI example referred to here `examples/run_controller.py`), a virtual controller is attached to BlueZ, and a second controller is attached to a Bumble stack, in the same app, which in this case is a simple virtual device that exposes a GATT service (both controllers run in the same process). One option is to use the same model as `run_controller.py` (i.e run both controllers as part of the same process, same python app, in which case they communicate directly via API calls). You'd of course replace the GATT service in the `run_controller.py` example with a heart rate service. The other option (more flexible but a bit more complex) is to run each controller in a separate python app/process, and have them communicate via a relay. If you look at the Link Relay doc, you should see an example of that. In this case, you'd have one process creating a controller attached to BlueZ (via VHCI) and to the relay, and a second process, running the heart rate monitor, also connected to the relay. The relay, of course, has to be started before both of those, so that they can connect to it. It is more flexible, because you're separating your heart rate monitor "app" in a standalone app, and can start/stop it independently. It is more complicated, because now you have 3 apps to run (the relay, the BlueZ<->relay bridge, and the HR<->Relay app).

**Comment by michael-barrow** [comment]
Thanks this is very helpful!

I know there are some limits with supported commands.

I am unable to connect to the virtual controller provided by `examples/run_controller.py` from `gatttool` so I want to check if what I am seeing is expected.

### Window A
Run the bumble example to connect a virtual controller to BlueZ stack
```
sudo chmod 766 /dev/vhci
python3 examples/run_controller.py F6:F7:F8:F9:FA:FB examples/device1.json vhci
```

### Window B
get available handles from virtual controller
```
gatttool -b F0:F1:F2:F3:F4:F5 -I
[F0:F1:F2:F3:F4:F5][LE]> connect
Attempting to connect to F0:F1:F2:F3:F4:F5
Error: connect error: Connection refused (111)
```

Similar steps work for a real ble device (heartrate monitor) in that I see a list of services after I connect successfully to the monitor from gatttool and do `primary`. A big difference with the real device is that `sudo hcitool lescan` shows the MAC address of the real heart rate monitor, but the bumble virtual MAC does not show if I try `lescan` in a separate terminal after starting the example.

What do you think?

**Comment by barbibulle** [comment]
In theory what you're describing here should work. I'll give it a try on an RPi to see if I can get it to work (I did a brief test with just advertising and scanning, and was able to see the virtual device in my `lescan`, but I have not played with `gatttool` yet.

**Comment by barbibulle** [comment]
I just ran some tests on a Raspeberry pi, and was able to verify that this scenario works.

The first issue you're running into is that you are not specifying which HCI device you want to use with `hcitool` (for `lescan`) and `gatttool`. The first thing to check after launching the `run_controller.py` example is which HCI device number the Linux kernel has allocated. If you don't have any other controller on the system, that would typically be `hci0`, but in your case, since it looks like you do have a real radio enabled, the second, virtual controller, would likely be at `hci1`.
Just running `hciconfig` will show you all the controllers. The virtual controller will be the one where it says `Bus: Virtual`.
Now, assuming your virtual controller is `hci1`, you would then use: `sudo hcitool -i hci1 lescan` to scan with the virtual controller,  and `gatttool -i hci1 -t random -b F0:F1:F2:F3:F4:F5 -I` for `gatttool`.

The second issue, which is a bit obscure I have to say, is that with Bluetooth LE, you need to specify if an address is public or random (it can't tell by just looking at the address). Here, we're using random addresses, and you need to let `gatttool` know about that with `-t random`.
With that options, and the right `-i hciX` selection, you will then be able to `connect` from `gatttool` and try any of the other discovery and read/write commands.
Here the output on my system (in my case, I don't have a physical controller, so my virtual controller is at `hci0`):
```
pi@raspberrypi:~/bumble $ gatttool -i hci0 -t random -b F0:F1:F2:F3:F4:F5 -I
[F0:F1:F2:F3:F4:F5][LE]> connect
Attempting to connect to F0:F1:F2:F3:F4:F5
Connection successful
[F0:F1:F2:F3:F4:F5][LE]> primary
attr handle: 0x0001, end grp handle: 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle: 0x0006, end grp handle: 0x0009 uuid: 0000180a-0000-1000-8000-00805f9b34fb
[F0:F1:F2:F3:F4:F5][LE]> characteristics
handle: 0x0002, char properties: 0x02, char value handle: 0x0003, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0004, char properties: 0x02, char value handle: 0x0005, uuid: 00002a01-0000-1000-8000-00805f9b34fb
handle: 0x0007, char properties: 0x02, char value handle: 0x0008, uuid: 00002a29-0000-1000-8000-00805f9b34fb
```

and

```
pi@raspberrypi:~/bumble $ sudo hcitool -i hci0 lescan
LE Scan ...
F0:F1:F2:F3:F4:F5 Bumble
F0:F1:F2:F3:F4:F5 Bumble
F0:F1:F2:F3:F4:F5 Bumble
F0:F1:F2:F3:F4:F5 Bumble
```

**Comment by michael-barrow** [comment]
Thanks! 

Once I specified `hci1` to either `hcitool` or `gatttool` I was successfully able to connect to the bumble device:

```
gatttool -i hci1 -t random -b F0:F1:F2:F3:F4:F5 -I
[F0:F1:F2:F3:F4:F5][LE]> connect
Attempting to connect to F0:F1:F2:F3:F4:F5
Connection successful
[F0:F1:F2:F3:F4:F5][LE]>
```

 I was then able to see the virtual device in the pi's bluetooth manager GUI, so clearly it is visible throughout the bluez stack
![bumble](https://user-images.githubusercontent.com/20428997/215220351-474cc8bf-8215-4d67-a334-bb2294889aa4.png)

Thanks for keeping this issue open until you were able to direct me as to how I can use bumble to create virtual devices visible to non-bumble applications on the pi via bluez.

If successful in the application I am trying to develop, do you have an example zoo or some other place people can link their bumble projects as recipes for others?

Cheers!
