### ISSUE TITLE
Connection to speaker app drops after few seconds

### ISSUE THREAD

**Issue by veaceslavgspot** [google/bumble#429]
I am launching the speaker app over NetSim with: `python3 ../apps/speaker/speaker.py android-netsim`. I am able to connect to the speaker from and Android Emulator (Pixel 7 and 8, API 34), but as soon as I start playing something, e.g: on Spotify or Youtube Music, the bluetooth connection drops after about 5 - 10 seconds.  

Any ideas on what could be wrong?

Speaker logs
---
```
UI HTTP server at http://127.0.0.1:7654
Speaker Name: Bumble Speaker
Speaker Bluetooth Address: DA:4C:10:DE:17:02
Speaker ready to play, codec=aac
Waiting for connection...
Connection: Connection(handle=0x0EFE, role=PERIPHERAL, self_address=DA:4C:10:DE:17:02/P, peer_address=DA:4C:10:DE:17:00/P)
Audio Stream Open
Sink Configuration:
  ServiceCapabilities(AVDTP_MEDIA_TRANSPORT_SERVICE_CATEGORY)
  ServiceCapabilities(AVDTP_MEDIA_CODEC_SERVICE_CATEGORY,media_type=AVDTP_AUDIO_MEDIA_TYPE,codec=A2DP_MPEG_2_4_AAC_CODEC_TYPE,codec_info=AacMediaCodecInformation(
  object_type:        MPEG_2_AAC_LC
  sampling_frequency: 44100
  channels:           2
  vbr:                0
  bitrate:            256000))
RTP Channel Open
WARNING:bumble.l2cap:No server for connection 0x0EFE on PSM 23
Sink Started
[81171 bytes in 109 packets] RTP(v=2,p=0,x=0,m=1,pt=96,sn=109,ts=110592,ssrc=2,csrcs=[],payload_size=739)
```

Android logs
----
```
2024-02-21 13:52:24.629   712-824   BluetoothManagerService system_server                        E  MESSAGE_BLUETOOTH_SERVICE_DISCONNECTED(1)
2024-02-21 13:52:24.635  4394-4394  BluetoothDevice         com.android.settings                 E  BT not enabled. Cannot get bond state
2024-02-21 13:52:24.635   712-824   BluetoothManagerService system_server                        E  MESSAGE_BLUETOOTH_SERVICE_DISCONNECTED(2)
2024-02-21 13:52:24.637   712-2052  BluetoothManagerService system_server                        E  Unable to unbind service with intent: Intent { act=android.bluetooth.IBluetoothA2dp cmp=com.google.android.bluetooth/com.android.bluetooth.a2dp.A2dpService }
                                                                                                    java.lang.IllegalArgumentException: Service not registered: com.android.server.bluetooth.BluetoothManagerService$ProfileServiceConnections@50bb3eb
                                                                                                    	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:2001)
                                                                                                    	at android.app.ContextImpl.unbindService(ContextImpl.java:2168)
                                                                                                    	at com.android.server.bluetooth.BluetoothManagerService.unbindBluetoothProfileService(BluetoothManagerService.java:1767)
                                                                                                    	at android.bluetooth.BluetoothProfileConnector.doUnbind(BluetoothProfileConnector.java:155)
                                                                                                    	at android.bluetooth.BluetoothProfileConnector.-$$Nest$mdoUnbind(Unknown Source:0)
                                                                                                    	at android.bluetooth.BluetoothProfileConnector$2.onServiceDisconnected(BluetoothProfileConnector.java:110)
                                                                                                    	at com.android.server.bluetooth.BluetoothManagerService$ProfileServiceConnections.onServiceDisconnected(BluetoothManagerService.java:2019)
                                                                                                    	at com.android.server.bluetooth.BluetoothManagerService$ProfileServiceConnections.binderDied(BluetoothManagerService.java:2035)
                                                                                                    	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:319)
                                                                                                    	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:704)
2024-02-21 13:52:24.639 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:24.641   712-890   AS.BtHelper             system_server                        E  onBtProfileDisconnected: Not a profile handled by BtHelper A2DP_SINK
2024-02-21 13:52:24.641  1006-1107  BluetoothDevice         com.android.systemui                 E  BT not enabled. Cannot get bond state
2024-02-21 13:52:24.643   712-890   AS.BtHelper             system_server                        E  onBtProfileDisconnected: Not a profile handled by BtHelper LE_AUDIO_BROADCAST
2024-02-21 13:52:24.643   712-890   AS.BtHelper             system_server                        E  onBtProfileDisconnected: Not a profile handled by BtHelper A2DP_SINK
2024-02-21 13:52:24.643   712-890   AS.BtHelper             system_server                        E  onBtProfileDisconnected: Not a profile handled by BtHelper LE_AUDIO_BROADCAST
2024-02-21 13:52:24.650 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:24.661 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:24.671 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Remote Device name
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Remote Device Alias
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Remote Device name
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Bluetooth Class
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Bluetooth Class
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Remote Device name
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Remote Device Alias
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Remote Device name
2024-02-21 13:52:25.131  1353-2576  BluetoothDevice         com.google.android.gms.persistent    E  BT not enabled. Cannot get Remote Device name
2024-02-21 13:52:25.641 30245-30248 android.ha...mpl.ranchu android.hardware.audio.service       E  setConnectedState:234 failure: Result::NOT_SUPPORTED
2024-02-21 13:52:25.642 30244-30244 APM_AudioPolicyManager  audioserver                          E  Error 2 while setting connected state for device AUDIO_DEVICE_OUT_BLUETOOTH_A2DP, @:SUPPRESSED
2024-02-21 13:52:25.642 30245-30248 android.ha...mpl.ranchu android.hardware.audio.service       E  setConnectedState:234 failure: Result::NOT_SUPPORTED
2024-02-21 13:52:25.643 30244-30244 APM_AudioPolicyManager  audioserver                          E  Error 1 while setting connected state for device AUDIO_DEVICE_OUT_BLUETOOTH_A2DP, @:SUPPRESSED
2024-02-21 13:52:25.648 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:25.658 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:25.670 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:25.683 30245-31954 BTAudioHalStream        android.hardware.audio.service       E  out_write: state=DISABLED failed to resume
2024-02-21 13:52:30.548 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: bta_av_a2dp_sdp_cback: peer xx:xx:xx:xx:17:02 A2DP service discovery failed
2024-02-21 13:52:30.548 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: bta_av_a2dp_sdp_cback: BTA_AV_SDP_DISC_FAIL_EVT: peer_addr=xx:xx:xx:xx:17:02
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: bta_av_conn_failed: peer_addr=xx:xx:xx:xx:17:02 open_status=0
2024-02-21 13:52:35.673 31983-32009 bluetooth               com.google.android.bluetooth         E  packages/modules/Bluetooth/system/bta/dm/bta_dm_pm.cc:377 bta_dm_pm_cback: Unable to find peer device...yet soldiering on...
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: get_connected_device: returning NULL
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: get_connected_device: returning NULL
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: get_connected_device: returning NULL
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: get_connected_device: returning NULL
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: get_connected_device: returning NULL
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: get_connected_device: returning NULL
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: btif_rc_get_device_by_bda: device not found, returning NULL!
2024-02-21 13:52:35.673 31983-32009 bt_btif                 com.google.android.bluetooth         E  packages/modules/Bluetooth/system/main/bte_logmsg.cc:105 LogMsg: btif_rc_check_handle_pending_play: p_dev NULL
```

**Comment by barbibulle** [comment]
Thanks for reporting this. I was able to reproduce this issue on the latest release of Android Studio, running an AVD with and Android U image. I'm investigating.

**Comment by barbibulle** [comment]
This is now fixed in recent versions of the Android emulator.
