### ISSUE TITLE
Bumble-hci-bridge returning 'LIBUSB_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by rsrikaan** [google/bumble#433]
Error
`bumble-hci-bridge android-netsim:_:8877,mode=controller usb:0
>>> connecting to HCI...
>>> connected
>>> connecting to HCI...
WARNING:bumble.transport.usb:←[31m!!! failed to open USB device: LIBUSB_ERROR_NOT_SUPPORTED [-12]←[0m
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Scripts\bumble-hci-bridge.exe\__main__.py", line 7, in <module>
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\apps\hci_bridge.py", line 104, in main
    asyncio.run(async_main())
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\apps\hci_bridge.py", line 56, in async_main
    async with await transport.open_transport_or_link(sys.argv[2]) as (
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\transport\__init__.py", line 214, in open_transport_or_link
    return await open_transport(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\transport\__init__.py", line 93, in open_transport
    transport = await _open_transport(scheme, spec)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\transport\__init__.py", line 165, in _open_transport
    return await open_usb_transport(spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\transport\usb.py", line 515, in open_usb_transport
    device = found.open()
             ^^^^^^^^^^^^
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb1\__init__.py", line 2055, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb1\__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "C:\Users\rsrikaan\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb1\__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorNotSupported: LIBUSB_ERROR_NOT_SUPPORTED [-12]`

Driver configs tried 
![image](https://github.com/google/bumble/assets/148060960/ca842ad7-e262-4315-9fd8-78cf3d99730c)
![image](https://github.com/google/bumble/assets/148060960/d3d4c37e-72d1-465c-b2d7-abdc59168ea6)

Any idea how to fix this?

**Comment by rsrikaan** [comment]
HI anyone who has successfully made bumble work in windows, could you provide details on your build? like what dongle, drivers, environment etc.

**Comment by barbibulle** [comment]
This works for me on a Windows 10 laptop. I'll see if I can find a few other windows machines to try on and try to reproduce the error you're seeing.
