### ISSUE TITLE
Controller object has no attribute advertising times [extended advertisement branch]

### ISSUE THREAD

**Issue by vChavezB** [google/bumble#469]
When running the bumble `controller.py` of branch `gbg/controller-extended-advertising` I get the following error when connecting to my Zephyr virtual bluetooth device:

```
ERROR:bumble.transport.common:!!! Exception in on_packet: 'Controller' object has no attribute 'advertising_times'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\transport\common.py", line 152, in feed_data
    self.sink.on_packet(bytes(self.packet))
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\controller.py", line 575, in on_packet
    self.on_hci_packet(HCI_Packet.from_bytes(packet))
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\controller.py", line 585, in on_hci_packet
    self.on_hci_command_packet(packet)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\controller.py", line 596, in on_hci_command_packet
    result = handler(command)
             ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\controller.py", line 1364, in on_hci_le_set_advertising_enable_command
    self.schedule_advertiser(self.legacy_advertiser, time.time())
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bumble\controller.py", line 1026, in schedule_advertiser
    heapq.heappush(self.advertising_times, (when, advertiser))
                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Controller' object has no attribute 'advertising_times'
```

**Comment by vChavezB** [comment]
I think it has to do that the variable is not initialized here

https://github.com/google/bumble/blob/07270240e34715d1b56a0cad995d664544bc3aad/bumble/controller.py#L515

**Comment by barbibulle** [comment]
Thanks for reporting this issue. I'll fix it ASAP.
