### ISSUE TITLE
Regression: unable to import Device due to type annotation error for Python 3.8

### ISSUE THREAD

**Issue by mogenson** [google/bumble#69]
Commit 78534b659a8cb4a2e7ece27a81be171abed92155 introduced a regression. A `TypeError` exception is raised when importing `Device`. I'm using Python 3.8 from the environment.yaml Conda environment. Python 3.8 is specified in setup.cfg as a supported Python version.

eg.

```
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bumble.device import Device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mogenson/Work/bumble/bumble/device.py", line 617, in <module>
    class Device(CompositeEventEmitter):
  File "/home/mogenson/Work/bumble/bumble/device.py", line 1600, in Device
    async def request_remote_name(self, remote: Connection | Address):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

@uael FYI

**Comment by mogenson** [comment]
Sorry, just realized this was fixed in ce9004f0ac4b7628c46fc3d34c008450398c9514

Closing issue!
