### ISSUE TITLE
Regression: cannot set Device.host - Host object has no attribute add_listener

### ISSUE THREAD

**Issue by mogenson** [google/bumble#70]
Since commit ce9004f0ac4b7628c46fc3d34c008450398c9514 setting the `host` member of a `Device` raises an AttributeError exception from l2cap.py.

Eg.

```
python -m asyncio
asyncio REPL 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from bumble.device import Device
>>> from bumble.host import Host
>>> from bumble.transport import open_transport
>>> device = Device()
>>> device.transport = await open_transport("usb:0")
>>> device.host = Host(device.transport.source, device.transport.sink)
Traceback (most recent call last):
  File "/home/mogenson/miniconda3/envs/bumble/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/mogenson/miniconda3/envs/bumble/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/mogenson/miniconda3/envs/bumble/lib/python3.8/asyncio/__main__.py", line 34, in callback
    coro = func()
  File "<console>", line 1, in <module>
  File "/home/mogenson/Work/bumble/bumble/device.py", line 773, in host
    self.l2cap_channel_manager.host = host
  File "/home/mogenson/Work/bumble/bumble/l2cap.py", line 1227, in host
    host.add_listener('disconnection', self.on_disconnection)
AttributeError: 'Host' object has no attribute 'add_listener'
>>> 
```

**Comment by mogenson** [comment]
Note, this also seems to be Python 3.8 specific. I don't have this problem with Python 3.9.
